@extends('rescon.layout')
@section('content')
@php $base = rtrim(url('/'), '/'); @endphp
<main id=page><header class=pagewidth><menu class=srm><a id=print-button class=hide href=javascript:window.print() role=button aria-label=Print><span class="t srt" role=tooltip>Print</span>
</a><a id=navigatorShare href=#share role=button aria-label=Share><span class="t srt" role=tooltip>Share</span>
</a><a id=copyPermalink class=hide href=javascript:navigator.clipboard.writeText(window.location.href) role=button aria-label="Copy URL"><span id=copy class="t srt" role=tooltip>Copy URL</span>
<span id=isCopying style=display:none>Copying...</span>
<span id=copyText style=display:none>Copy URL</span></a></menu><button id=back class=hide type=button onclick=history.back() aria-label="Go Back">
<span class="t srt" role=tooltip>Go Back</span></button><details class=presentation aria-expanded=true id=has-breadcrumb open><summary id=breadcrumb tabindex=-1><span>Breadcrumb</span></summary><nav aria-labelledby=breadcrumb><ul role=presentation class=breadcrumb><li><a href={{ $base }}/rescon/detail/ aria-current=true>Event Details</a></li><li><a href aria-current=page tabindex=-1>Programme</a></li></ul></nav></details></header><div id=top role=presentation></div><article id=main-article class="pagewidth rm" role=document aria-labelledby=title data-pagefind-body><header aria-labelledby=title><hgroup data-bionread-safe><h1 id=title data-pagefind-meta=title>Programme</h1><p class=subtitle role=doc-subtitle>Schedule, sessions and key activities shaping the event !</p></hgroup><div id=doc-author class="textsw author"></div><div class=date-has-label><time class=doc-publish-date datetime=2025-09-03T00:00:00+05:30 data-time-label="Published on">3 September 2025</time>
<time class=doc-lastmod-date datetime=2026-08-26T00:00:00+05:30 data-time-label="Modified on">26 August 2026</time></div></header><section aria-labelledby=title id=content data-bionread-safe><p>To be updated !</p></section><footer><nav id=keywords aria-label=Tags><span>Tags:&nbsp;</span><ul class=delimiter role=presentation><li><a href={{ $base }}/rescon/tags/programme/>Programme</a></li><li><a href={{ $base }}/rescon/tags/updates/>Updates</a></li></ul></nav></footer></article><hr class=hide style="margin:1in 0"><div id=contentinfo class=pagewidth role=contentinfo data-pagefind-ignore=all><nav id=related aria-label="You might also like"><strong class=section-title>You might also like</strong><ol><li><a href={{ $base }}/rescon/detail/contact/>Contact</a></li><li><a href={{ $base }}/rescon/detail/dates/>Important Dates</a></li></ol></nav><div id=colophon style=display:none aria-live=polite><strong class=section-title>Colophon</strong><div><div id=qr role=img aria-label="QR code"></div><div class=verbose><div class=has-aria-label-top aria-label=Programme><span>{{ $base }}/rescon/detail/programme/</span></div><div><span>This page was accessed on: </span><time id=time-stamp></time></div></div></div></div><div id=has-timeline><strong class=section-title>Redaction History</strong><ol aria-label="Redaction History"><li><time datetime=2025-09-03T00:00:00+05:30>3 September 2025</time>
<span>(Published)</span></li><li><time datetime=2026-08-26T00:00:00+05:30>26 August 2026</time>
<span>(Modified)</span></li></ol><p>Some information might change over time, we'll keep redaction up to date.</p></div><details class=presentation aria-expanded=true id=has-share open><summary id=share tabindex=-1><span>Share</span></summary><nav aria-labelledby=share><ul role=presentation class="share srm"><li id=has-mastodon><form class=form id=mastodon action=//sharetomastodon.github.io/ target=_blank rel="noopener noreferrer"><input id=mastodonTitle type=hidden name=title value=Programme>
<input id=mastodonPermalink type=hidden name=url value={{ $base }}/rescon/detail/programme/>
<input id=mastodonText type=hidden name=text value="Programme {{ $base }}/rescon/detail/programme/" disabled>
<input id=mastodonInstance type=url class="ldots form__input" placeholder="Enter Mastodon instance (https://www.example.com)" aria-label="Mastodon instance URL">
<button class=form__button type=submit aria-label="Share on Mastodon">
<i class="icon mastodon sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Mastodon</span></button></form></li><li><a href="mailto:?subject=Programme&body=https%3a%2f%2frnd.iitb.ac.in%2frescon%2fen%2fdetail%2fprogramme%2f" role=button aria-label="Share on Email"><i class="email sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Email</span></a></li><li><a href="whatsapp://send?text=Programme%20https%3a%2f%2frnd.iitb.ac.in%2frescon%2fen%2fdetail%2fprogramme%2f" role=button aria-label="Share on Whatsapp"><i class="whatsapp sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Whatsapp</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://telegram.me/share/url?text=Programme&amp;url={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Telegram in new tab"><i class="telegram sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Telegram</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://bsky.app/intent/compose?text=Programme&amp;url={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Bluesky in new tab"><i class="bluesky sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Bluesky</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://facebook.com/sharer/sharer.php?u={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Facebook in new tab"><i class="facebook sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Facebook</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://news.ycombinator.com/submitlink?u={{ $base }}/rescon/detail/programme/&amp;t=Programme" role=button aria-label="Share on Hackernews in new tab"><i class="hackernews sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Hackernews</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://www.linkedin.com/shareArticle?mini=true&amp;url={{ $base }}/rescon/detail/programme/&amp;title=Programme&amp;summary=Programme&amp;source={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Linkedin in new tab"><i class="linkedin sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Linkedin</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://pinterest.com/pin/create/button/?url={{ $base }}/rescon/detail/programme/&amp;media={{ $base }}/rescon/detail/programme/&amp;description=Programme" role=button aria-label="Share on Pinterest in new tab"><i class="pinterest sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Pinterest</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://reddit.com/submit/?url={{ $base }}/rescon/detail/programme/&amp;resubmit=true&amp;title=Programme" role=button aria-label="Share on Reddit in new tab"><i class="reddit sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Reddit</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://www.tumblr.com/widgets/share/tool?posttype=link&amp;title=Programme&amp;caption=Programme&amp;content={{ $base }}/rescon/detail/programme/&amp;canonicalUrl={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Tumblr in new tab"><i class="tumblr sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Tumblr</span></a></li><li><a rel="noopener noreferrer" target=_blank href="http://vk.com/share.php?title=Programme&amp;url={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Vk in new tab"><i class="vk sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Vk</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://twitter.com/intent/tweet/?text=Programme&amp;url={{ $base }}/rescon/detail/programme/" role=button aria-label="Share on Twitter in new tab"><i class="twitter sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Twitter</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://www.xing.com/app/user?op=share;url={{ $base }}/rescon/detail/programme/;title=Programme" role=button aria-label="Share on Xing in new tab"><i class="xing sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Xing</span></a></li></ul></nav></details></div><hr class=hide><footer id=main-footer><div class="column column--multicols pagewidth" style=--multicols:2><div id=main-footer-primary><p><strong>Address</strong></p><p>Office of Dean (R & D),<br>2nd floor, Rahul Bajaj Technology Innovation Centre (RBTIC),<br>Opp. VMCC, IIT Bombay,<br>Powai, Mumbai, Maharashtra - 400076<br><br></p></div><div id=main-footer-secondary class=column style=--col:10rem><div><p><strong>Quick Links</strong></p><ul><li><a href={{ $base }}/rescon/>Home</a></li><li><a href={{ $base }}/rescon/#aboutrescon>About ResCon</a></li><li><a href={{ $base }}/rescon/detail/programme/>Programme</a></li><li><a href={{ $base }}/rescon/detail/speakers/>Speakers</a></li><li><a href={{ $base }}/rescon/detail/dates/>Dates</a></li><li><a href={{ $base }}/rescon/detail/gallery/>Gallery</a></li><li><a href={{ $base }}/rescon/detail/contact/>Contact</a></li><li><a href=https://unstop.com/p/techconnect26-research-poster-presentation-competition-iit-bombay-1749312>Register</a></li></ul></div><div><p><strong>Organizers</strong> (2025)</p><ul><li><a class=footer-img-link href=https://iitbresearchpark.com/ target=_blank><img src=https://marketingandbusinessdevelopment-iitbrp.s3.ap-south-1.amazonaws.com/aspire-website-revamp-media/public/brand-logo/aspire-logo.png alt=Aspire>
Aspire</a></li><li><a class=footer-img-link href=https://ugac-iitb.github.io/UGAC-IITB/divisions/4 target=_blank><img src=/rescon-assets/media/images/logo/logo.enpower.bg_transparent.fg_light.png alt=EnPoWER>
EnPoWER</a></li><li><a class=footer-img-link href=https://acr.iitbombay.org/ target=_blank><img src=/rescon-assets/media/images/logo/logo.drf.bg_transparent.png alt="IITB DRF">
IITB DRF</a></li><li><a class=footer-img-link href=https://www.cep.iitb.ac.in/ target=_blank><img src=https://www.cep.iitb.ac.in/assets/img/eo_iitb.png alt="IITB EO">
IITB EO</a></li><li><a class=footer-img-link href=https://rnd.iitb.ac.in/ target=_blank><img src=/rescon-assets/media/images/logo/logo.ircc.bg_light.fg_dark.png alt=IRCC>
IRCC</a></li><li><a class=footer-img-link href=https://sineiitb.org/ target=_blank><img src=https://sineiitb.org/Header/logo.png alt=SINE>
SINE</a></li><li><a class=footer-img-link href=https://tihiitb.org/ target=_blank><img src=https://tihiitb.org/wp-content/uploads/2023/10/TIH-logo.png alt=TIH>
TIH</a></li><li><a href=/>TechConnect</a></li><li><a href=https://ugac-iitb.github.io/UGAC-IITB/>UGAC</a></li></ul></div></div></div><div id=unified-footer><p id=license style=text-transform:none>© IIT Bombay - ResCon 2026 | TechConnect 2026 (IRCC)</p><nav id=menu-footer class=has-aria-label-top aria-label="Let's keep in touch!"><ul role=presentation><li><a href=https://www.instagram.com/enpower_iitb aria-label=instagram><i class=icon>instagram</i>
<span class=t role=tooltip>instagram</span></a></li></ul></nav></div></footer></main>
@endsection
