@extends('rescon.layout')
@section('content')
@php $base = rtrim(url('/'), '/'); @endphp
<main id=term><header class=pagewidth><menu class=srm><a id=print-button class=hide href=javascript:window.print() role=button aria-label=Print><span class="t srt" role=tooltip>Print</span>
</a><a id=navigatorShare href="javascript:navigator.share({title: document.title, url: window.location.href})" role=button aria-label=Share><span class="t srt" role=tooltip>Share</span>
</a><a id=copyPermalink class=hide href=javascript:navigator.clipboard.writeText(window.location.href) role=button aria-label="Copy URL"><span id=copy class="t srt" role=tooltip>Copy URL</span>
<span id=isCopying style=display:none>Copying...</span>
<span id=copyText style=display:none>Copy URL</span></a></menu><button id=back class=hide type=button onclick=history.back() aria-label="Go Back">
<span class="t srt" role=tooltip>Go Back</span></button><details class=presentation aria-expanded=true id=has-breadcrumb open><summary id=breadcrumb tabindex=-1><span>Breadcrumb</span></summary><nav aria-labelledby=breadcrumb><ul role=presentation class=breadcrumb><li><a href={{ $base }}/rescon/tags/ aria-current=true>Tags</a></li><li><a href aria-current=page tabindex=-1>Dates</a></li></ul></nav></details></header><div id=top role=presentation></div><section id=list-posts class=pagewidth aria-labelledby=list-post-heading><header id=tag class=section-title><strong id=list-post-heading>Posts on: <span class=tag>Dates</span></strong></header><div class="list-year textwidth" role=listitem aria-labelledby=2025><strong id=2025 class=section-title role=heading aria-level=1>2025</strong><div role=list aria-label=2025><div role=listitem aria-labelledby=y2025-September><details aria-expanded=true class=list-month open><summary class="has-post section-title" id=y2025-September role=heading aria-level=2 aria-label=September aria-description="(1 Post)">September</summary><ul class=list-day role=presentation><li><a class=has-pre href={{ $base }}/rescon/detail/dates/ aria-label="Important Dates" aria-description="3 Sep "><span>Important Dates</span></a></li></ul></details></div></div></div></section><hr class=hide><footer id=main-footer><div class="column column--multicols pagewidth" style=--multicols:2><div id=main-footer-primary><p><strong>Address</strong></p><p>Office of Dean (R & D),<br>2nd floor, Rahul Bajaj Technology Innovation Centre (RBTIC),<br>Opp. VMCC, IIT Bombay,<br>Powai, Mumbai, Maharashtra - 400076<br><br></p></div><div id=main-footer-secondary class=column style=--col:10rem><div><p><strong>Quick Links</strong></p><ul><li><a href={{ $base }}/rescon/>Home</a></li><li><a href={{ $base }}/rescon/#aboutrescon>About ResCon</a></li><li><a href={{ $base }}/rescon/detail/programme/>Programme</a></li><li><a href={{ $base }}/rescon/detail/speakers/>Speakers</a></li><li><a href={{ $base }}/rescon/detail/dates/>Dates</a></li><li><a href={{ $base }}/rescon/detail/gallery/>Gallery</a></li><li><a href={{ $base }}/rescon/detail/contact/>Contact</a></li><li><a href=https://unstop.com/p/techconnect26-research-poster-presentation-competition-iit-bombay-1749312>Register</a></li></ul></div><div><p><strong>Organizers</strong> (2025)</p><ul><li><a class=footer-img-link href=https://iitbresearchpark.com/ target=_blank><img src=https://marketingandbusinessdevelopment-iitbrp.s3.ap-south-1.amazonaws.com/aspire-website-revamp-media/public/brand-logo/aspire-logo.png alt=Aspire>
Aspire</a></li><li><a class=footer-img-link href=https://ugac-iitb.github.io/UGAC-IITB/divisions/4 target=_blank><img src=/rescon-assets/media/images/logo/logo.enpower.bg_transparent.fg_light.png alt=EnPoWER>
EnPoWER</a></li><li><a class=footer-img-link href=https://acr.iitbombay.org/ target=_blank><img src=/rescon-assets/media/images/logo/logo.drf.bg_transparent.png alt="IITB DRF">
IITB DRF</a></li><li><a class=footer-img-link href=https://www.cep.iitb.ac.in/ target=_blank><img src=https://www.cep.iitb.ac.in/assets/img/eo_iitb.png alt="IITB EO">
IITB EO</a></li><li><a class=footer-img-link href=https://rnd.iitb.ac.in/ target=_blank><img src=/rescon-assets/media/images/logo/logo.ircc.bg_light.fg_dark.png alt=IRCC>
IRCC</a></li><li><a class=footer-img-link href=https://sineiitb.org/ target=_blank><img src=https://sineiitb.org/Header/logo.png alt=SINE>
SINE</a></li><li><a class=footer-img-link href=https://tihiitb.org/ target=_blank><img src=https://tihiitb.org/wp-content/uploads/2023/10/TIH-logo.png alt=TIH>
TIH</a></li><li><a href=/>TechConnect</a></li><li><a href=https://ugac-iitb.github.io/UGAC-IITB/>UGAC</a></li></ul></div></div></div><div id=unified-footer><p id=license style=text-transform:none>© IIT Bombay - ResCon 2026 | TechConnect 2026 (IRCC)</p><nav id=menu-footer class=has-aria-label-top aria-label="Let's keep in touch!"><ul role=presentation><li><a href=https://www.instagram.com/enpower_iitb aria-label=instagram><i class=icon>instagram</i>
<span class=t role=tooltip>instagram</span></a></li></ul></nav></div></footer></main>
@endsection
