<!doctype html>
<html lang=en-IN dir=ltr>
<head><meta name=generator content="Hugo 0.148.2"><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1"><meta name=viewport content="width=device-width,initial-scale=1"><title>{{ $title }}</title><meta name=author content><meta name=description content="{{ $description }}"><meta name=keywords content="{{ $keywords }}"><link rel=canonical href="{{ url($canonical) }}"><link rel=icon type=image/png href=/media/images/logo/logo.favicon.techconnect.bg_dark.fg_light.png sizes=96x96><meta name=apple-mobile-web-app-title content="TechConnect 2026"><meta name=twitter:card content="summary"><meta name=twitter:title content="{{ $title }}"><meta name=twitter:description content="{{ $description }}"><meta property="og:title" content="{{ $title }}"><meta property="og:description" content="{{ $description }}"><meta property="og:type" content="website"><meta property="og:url" content="{{ url($canonical) }}"><meta property="og:site_name" content="TechConnect 2026"><link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel=stylesheet integrity=sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC crossorigin=anonymous><script src=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js integrity=sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM crossorigin=anonymous></script><script src=https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js integrity=sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p crossorigin=anonymous></script><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css><script src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin=anonymous referrerpolicy=no-referrer></script><script src=/js/hugo-brewm.min.js defer></script><link rel=stylesheet href=/css/hugo-brewm.min.css>@stack('head')</head>
<body>
@include('partials.header', ['skip' => $skip ?? '#content'])
@yield('content')
@include('partials.footer')
</body>
</html>
