@extends('layouts.app')
@section('content')
@php $base = rtrim(url('/'), '/'); @endphp
<main id=page><header class=pagewidth><menu class=srm><a id=print-button class=hide href=javascript:window.print() role=button aria-label=Print><span class="t srt" role=tooltip>Print</span>
</a><a id=navigatorShare href=#share role=button aria-label=Share><span class="t srt" role=tooltip>Share</span>
</a><a id=copyPermalink class=hide href=javascript:navigator.clipboard.writeText(window.location.href) role=button aria-label="Copy URL"><span id=copy class="t srt" role=tooltip>Copy URL</span>
<span id=isCopying style=display:none>Copying...</span>
<span id=copyText style=display:none>Copy URL</span></a></menu><button id=back class=hide type=button onclick=history.back() aria-label="Go Back">
<span class="t srt" role=tooltip>Go Back</span></button><details class=presentation aria-expanded=true id=has-breadcrumb open><summary id=breadcrumb tabindex=-1><span>Breadcrumb</span></summary><nav aria-labelledby=breadcrumb><ul role=presentation class=breadcrumb><li><a href={{ $base }}/event/ aria-current=true>Events & Details</a></li><li><a href aria-current=page tabindex=-1>Team</a></li></ul></nav></details></header><div id=top role=presentation></div><article id=main-article class="pagewidth rm" role=document aria-labelledby=title data-pagefind-body><header aria-labelledby=title><hgroup data-bionread-safe><h1 id=title data-pagefind-meta=title>Team</h1><p class=subtitle role=doc-subtitle>Meet the minds behind the TechConnect 2026 !</p></hgroup><div id=doc-author class="textsw author"></div><div class=date-has-label><time class=doc-publish-date datetime=2025-09-03T00:00:00+05:30 data-time-label="Published on">3 September 2025</time>
<time class=doc-lastmod-date datetime=2026-09-16T00:00:00+05:30 data-time-label="Modified on">16 September 2026</time></div></header><section aria-labelledby=title id=content data-bionread-safe><h1 id=faculty-coordinators>Faculty Coordinators</h1><br><p><div id=teamfacultycoordinators class="row align-items-center justify-content-evenly
g-4 p-1" tabindex=0><div class="col col-12
col-sm-12
col-md-6
col-lg-5
align-items-center justify-content-center"><div class="card bg-transparent card-div" tabindex=0><img class="card-img-top img-div" src=/media/images/techconnect/profile/team/SanjogNagarkar.jpg alt="Prof. Sanjog Nagarkar" loading=lazy></img><div class="card-body text-center"><h5 class=card-title>Prof. Sanjog Nagarkar</h5><p class=card-text>(<em>Faculty Coordinator</em>)</p><div class="card-text btn-group mx-auto align-self-center" role=group aria-label=Socials><a href=tel:+912225767190 target=_blank class="btn btn-div p-1 card-social-link" aria-label=telephone><i class="bi bi-telephone"></i><span class=t role=tooltip>telephone: +91-22-2576-7190
</span></a><a href=mailto:sanjog.na@chem.iitb.ac.in target=_blank class="btn btn-div p-1 card-social-link" aria-label=email><i class="bi bi-envelope"></i><span class=t role=tooltip>email: sanjog.na@chem.iitb.ac.in</span></a></div></div></div></div><div class="col col-12
col-sm-12
col-md-6
col-lg-5
align-items-center justify-content-center"><div class="card bg-transparent card-div" tabindex=0><img class="card-img-top img-div" src=/media/images/techconnect/profile/team/DeepooKumar.jpg alt="Prof. Deepoo Kumar" loading=lazy></img><div class="card-body text-center"><h5 class=card-title>Prof. Deepoo Kumar</h5><p class=card-text>(<em>Faculty Coordinator</em>)</p><div class="card-text btn-group mx-auto align-self-center" role=group aria-label=Socials><a href=tel:+912225767647 target=_blank class="btn btn-div p-1 card-social-link" aria-label=telephone><i class="bi bi-telephone"></i><span class=t role=tooltip>telephone: +91-22-2576-7647
</span></a><a href=mailto:deepook@iitb.ac.in target=_blank class="btn btn-div p-1 card-social-link" aria-label=email><i class="bi bi-envelope"></i><span class=t role=tooltip>email: deepook@iitb.ac.in</span></a></div></div></div></div></div></p><br><br><h1 id=staff-coordinators>Staff Coordinators</h1><br><p><div id=teamstaffcoordinators class="row align-items-center justify-content-evenly
g-4 p-1" tabindex=0><div class="col col-12
col-sm-12
col-md-4
col-lg-4
align-items-center justify-content-center"><div class="card bg-transparent card-div" tabindex=0><img class="card-img-top img-div" src=/media/images/techconnect/profile/team/TanviMehta.jpg alt="Ms. Tanvi Mehta" loading=lazy></img><div class="card-body text-center"><h5 class=card-title>Ms. Tanvi Mehta</h5><p class=card-text>(<em>Staff Coordinator</em>)</p><div class="card-text btn-group mx-auto align-self-center" role=group aria-label=Socials><a href=tel:+912221593903 target=_blank class="btn btn-div p-1 card-social-link" aria-label=telephone><i class="bi bi-telephone"></i><span class=t role=tooltip>telephone: +91-22-2159-3903
</span></a><a href=mailto:tanvi.mehta@iitb.ac.in target=_blank class="btn btn-div p-1 card-social-link" aria-label=email><i class="bi bi-envelope"></i><span class=t role=tooltip>email: tanvi.mehta@iitb.ac.in</span></a></div></div></div></div><div class="col col-12
col-sm-12
col-md-4
col-lg-4
align-items-center justify-content-center"><div class="card bg-transparent card-div" tabindex=0><img class="card-img-top img-div" src=/media/images/techconnect/profile/team/PreetiTopagi.jpg alt="Ms. Preeti Topagi" loading=lazy></img><div class="card-body text-center"><h5 class=card-title>Ms. Preeti Topagi</h5><p class=card-text>(<em>Staff Coordinator</em>)</p><div class="card-text btn-group mx-auto align-self-center" role=group aria-label=Socials><a href=tel:+912221593912 target=_blank class="btn btn-div p-1 card-social-link" aria-label=telephone><i class="bi bi-telephone"></i><span class=t role=tooltip>telephone: +91-22-2159-3912
</span></a><a href=mailto:preetitopagi@ircc.iitb.ac.in target=_blank class="btn btn-div p-1 card-social-link" aria-label=email><i class="bi bi-envelope"></i><span class=t role=tooltip>email: preetitopagi@ircc.iitb.ac.in</span></a></div></div></div></div><div class="col col-12
col-sm-12
col-md-4
col-lg-4
align-items-center justify-content-center"><div class="card bg-transparent card-div" tabindex=0><img class="card-img-top img-div" src=/media/images/techconnect/profile/team/AvaniNileshKadam.jpg alt="Ms. Avani Nilesh Kadam" loading=lazy></img><div class="card-body text-center"><h5 class=card-title>Ms. Avani Nilesh Kadam</h5><p class=card-text>(<em>Staff Coordinator</em>)</p><div class="card-text btn-group mx-auto align-self-center" role=group aria-label=Socials><a href=tel:+912221593955 target=_blank class="btn btn-div p-1 card-social-link" aria-label=telephone><i class="bi bi-telephone"></i><span class=t role=tooltip>telephone: +91-22-2159-3955
</span></a><a href=mailto:avani@ircc.iitb.ac.in target=_blank class="btn btn-div p-1 card-social-link" aria-label=email><i class="bi bi-envelope"></i><span class=t role=tooltip>email: avani@ircc.iitb.ac.in</span></a></div></div></div></div></div></p><br><br><h1 id=student-coordinators>Student Coordinators</h1><br><p><div id=teamstudentcoordinators class="row align-items-center justify-content-evenly
g-4 p-1" tabindex=0><div class="col col-12
col-sm-12
col-md-4
col-lg-4
align-items-center justify-content-center"><div class="card bg-transparent card-div" tabindex=0><img class="card-img-top img-div" src=/media/images/techconnect/profile/team/Ananthakrishnan.jpg alt="Ananthakrishnan B" loading=lazy></img><div class="card-body text-center"><h5 class=card-title>Ananthakrishnan B</h5><p class=card-text>(<em>Overall Chair</em>)</p><div class="card-text btn-group mx-auto align-self-center" role=group aria-label=Socials><a href=tel:+919319140171 target=_blank class="btn btn-div p-1 card-social-link" aria-label=telephone><i class="bi bi-telephone"></i><span class=t role=tooltip>telephone: +91-9319140171
</span></a><a href=mailto:22n0408@iitb.ac.in target=_blank class="btn btn-div p-1 card-social-link" aria-label=email><i class="bi bi-envelope"></i><span class=t role=tooltip>email: 22n0408@iitb.ac.in
</span></a><a href=http://www.linkedin.com/in/ananthakrishnan-b-b0889722a target=_blank class="btn btn-div p-1 card-social-link" aria-label=linkedin><i class=icon>linkedin
</i><span class=t role=tooltip>linkedin: ananthakrishnan-b-b0889722a</span></a></div></div></div></div></p></div></section><footer><nav id=keywords aria-label=Tags><span>Tag:&nbsp;</span><ul class=inline role=presentation><li><a href={{ $base }}/tags/team/>Team</a></li></ul></nav></footer></article><hr class=hide style="margin:1in 0"><div id=contentinfo class=pagewidth role=contentinfo data-pagefind-ignore=all><div id=colophon style=display:none aria-live=polite><strong class=section-title>Colophon</strong><div><div id=qr role=img aria-label="QR code"></div><div class=verbose><div class=has-aria-label-top aria-label=Team><span>{{ $base }}/event/team/</span></div><div><span>This page was accessed on: </span><time id=time-stamp></time></div></div></div></div><div id=has-timeline><strong class=section-title>Redaction History</strong><ol aria-label="Redaction History"><li><time datetime=2025-09-03T00:00:00+05:30>3 September 2025</time>
<span>(Published)</span></li><li><time datetime=2026-09-16T00:00:00+05:30>16 September 2026</time>
<span>(Modified)</span></li></ol><p>Some information might change over time, we'll keep redaction up to date.</p></div><details class=presentation aria-expanded=true id=has-share open><summary id=share tabindex=-1><span>Share</span></summary><nav aria-labelledby=share><ul role=presentation class="share srm"><li id=has-mastodon><form class=form id=mastodon action=//sharetomastodon.github.io/ target=_blank rel="noopener noreferrer"><input id=mastodonTitle type=hidden name=title value=Team>
<input id=mastodonPermalink type=hidden name=url value={{ $base }}/event/team/>
<input id=mastodonText type=hidden name=text value="Team {{ $base }}/event/team/" disabled>
<input id=mastodonInstance type=url class="ldots form__input" placeholder="Enter Mastodon instance (https://www.example.com)" aria-label="Mastodon instance URL">
<button class=form__button type=submit aria-label="Share on Mastodon">
<i class="icon mastodon sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Mastodon</span></button></form></li><li><a href="mailto:?subject=Team&body=https%3a%2f%2frnd.iitb.ac.in%2ftechconnect%2fen%2fevent%2fteam%2f" role=button aria-label="Share on Email"><i class="email sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Email</span></a></li><li><a href="whatsapp://send?text=Team%20https%3a%2f%2frnd.iitb.ac.in%2ftechconnect%2fen%2fevent%2fteam%2f" role=button aria-label="Share on Whatsapp"><i class="whatsapp sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Whatsapp</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://telegram.me/share/url?text=Team&amp;url={{ $base }}/event/team/" role=button aria-label="Share on Telegram in new tab"><i class="telegram sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Telegram</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://bsky.app/intent/compose?text=Team&amp;url={{ $base }}/event/team/" role=button aria-label="Share on Bluesky in new tab"><i class="bluesky sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Bluesky</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://facebook.com/sharer/sharer.php?u={{ $base }}/event/team/" role=button aria-label="Share on Facebook in new tab"><i class="facebook sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Facebook</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://news.ycombinator.com/submitlink?u={{ $base }}/event/team/&amp;t=Team" role=button aria-label="Share on Hackernews in new tab"><i class="hackernews sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Hackernews</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://www.linkedin.com/shareArticle?mini=true&amp;url={{ $base }}/event/team/&amp;title=Team&amp;summary=Team&amp;source={{ $base }}/event/team/" role=button aria-label="Share on Linkedin in new tab"><i class="linkedin sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Linkedin</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://pinterest.com/pin/create/button/?url={{ $base }}/event/team/&amp;media={{ $base }}/event/team/&amp;description=Team" role=button aria-label="Share on Pinterest in new tab"><i class="pinterest sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Pinterest</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://reddit.com/submit/?url={{ $base }}/event/team/&amp;resubmit=true&amp;title=Team" role=button aria-label="Share on Reddit in new tab"><i class="reddit sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Reddit</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://www.tumblr.com/widgets/share/tool?posttype=link&amp;title=Team&amp;caption=Team&amp;content={{ $base }}/event/team/&amp;canonicalUrl={{ $base }}/event/team/" role=button aria-label="Share on Tumblr in new tab"><i class="tumblr sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Tumblr</span></a></li><li><a rel="noopener noreferrer" target=_blank href="http://vk.com/share.php?title=Team&amp;url={{ $base }}/event/team/" role=button aria-label="Share on Vk in new tab"><i class="vk sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Vk</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://twitter.com/intent/tweet/?text=Team&amp;url={{ $base }}/event/team/" role=button aria-label="Share on Twitter in new tab"><i class="twitter sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Twitter</span></a></li><li><a rel="noopener noreferrer" target=_blank href="https://www.xing.com/app/user?op=share;url={{ $base }}/event/team/;title=Team" role=button aria-label="Share on Xing in new tab"><i class="xing sri" aria-hidden=true></i>
<span class="t srt" role=tooltip>Share on Xing</span></a></li></ul></nav></details></div><hr class=hide><footer id=main-footer><div class="column column--multicols pagewidth" style=--multicols:2><div id=main-footer-primary><p><strong>Address</strong></p><p>Office of Dean (R & D),<br>2nd floor, Rahul Bajaj Technology Innovation Centre (RBTIC),<br>Opp. VMCC, IIT Bombay,<br>Powai, Mumbai, Maharashtra - 400076<br><br></p></div><div id=main-footer-secondary class=column style=--col:10rem><div><p><strong>Quick Links</strong></p><ul><li><a href={{ $base }}/event/about/>About</a></li><li><a href={{ $base }}/>Home</a></li><li><a href={{ $base }}/#abouttechconnect>About TechConnect</a></li><li><a href=https://rnd.iitb.ac.in/techconnect/media/files/techconnect/handout/book.techconnect.2025.pdf>Event compendium - PDF (2025)</a></li><li><a href={{ $base }}/event/exhibition/>Exhibition</a></li><li><a href={{ $base }}/event/symposium/>Symposium</a></li><li><a href={{ $base }}/rescon/>ResCon</a></li><li><a href={{ $base }}/event/contact/>Contact</a></li><li><a href={{ $base }}/event/team/>Team</a></li><li><a href={{ $base }}/event/gallery/>Gallery</a></li><li><a href={{ $base }}/event/highlights/>2024 Highlights</a></li></ul></div><div><p><strong>Organizers</strong> (2025)</p><ul><li><a class=footer-img-link href=https://iitbresearchpark.com/ target=_blank><img src=https://marketingandbusinessdevelopment-iitbrp.s3.ap-south-1.amazonaws.com/aspire-website-revamp-media/public/brand-logo/aspire-logo.png alt=Aspire>
Aspire</a></li><li><a class=footer-img-link href=https://acr.iitbombay.org/ target=_blank><img src=/media/images/logo/logo.drf.bg_transparent.png alt="IITB DRF">
IITB DRF</a></li><li><a class=footer-img-link href=https://www.cep.iitb.ac.in/ target=_blank><img src=https://www.cep.iitb.ac.in/assets/img/eo_iitb.png alt="IITB EO">
IITB EO</a></li><li><a class=footer-img-link href=https://rnd.iitb.ac.in/ target=_blank><img src=/media/images/logo/logo.ircc.bg_light.fg_dark.png alt=IRCC>
IRCC</a></li><li><a class=footer-img-link href=https://sineiitb.org/ target=_blank><img src=https://sineiitb.org/Header/logo.png alt=SINE>
SINE</a></li><li><a class=footer-img-link href=https://tihiitb.org/ target=_blank><img src=https://tihiitb.org/wp-content/uploads/2023/10/TIH-logo.png alt=TIH>
TIH</a></li></ul></div></div></div><div id=unified-footer><p id=license style=text-transform:none>© IIT Bombay - TechConnect 2026 (IRCC)</p><nav id=menu-footer class=has-aria-label-top aria-label="Let's keep in touch!"><ul role=presentation><li><a href=mailto:techconnect2025@ircc.iitb.ac.in aria-label=email><i class=icon>email</i>
<span class=t role=tooltip>email</span></a></li></ul></nav></div></footer></main>
@endsection
