@php $base = rtrim(url('/'), '/'); @endphp
<header class=pagewidth><div id=background-header class=background aria-hidden=true><div class=grain hidden></div></div><nav aria-label=Bypass><a id=to-content href={{ $skip ?? '#content' }} aria-label="Skip to Main Content"><span>Skip to Main Content</span>
<kbd class=key aria-hidden=true>c</kbd>
<span class=screening aria-hidden=true></span></a></nav><a id=logo class="customlogo logolight" href=https://iitb.ac.in/ target=_blank><img class=customlogo-img src=/rescon-assets/media/images/logo/logo.iitb.bg_transparent.fg_light.png alt=IITB>
</a><a id=logo class="customlogo logolight" href=https://ugac-iitb.github.io/UGAC-IITB/divisions/4 target=_blank><img class=customlogo-img src=/rescon-assets/media/images/logo/logo.enpower.bg_transparent.fg_light.png alt=EnPoWER>
</a><a id=logo class="customlogo logodark" href=https://iitb.ac.in/ target=_blank><img class=customlogo-img src=/rescon-assets/media/images/logo/logo.iitb.bg_transparent.fg_dark.png alt=IITB>
</a><a id=logo class="customlogo logodark" href=https://ugac-iitb.github.io/UGAC-IITB/divisions/4 target=_blank><img class=customlogo-img src=/rescon-assets/media/images/logo/logo.enpower.bg_transparent.fg_dark.png alt=EnPoWER>
</a><a id=logo href={{ $base }}/rescon/ aria-label="ResCon 2026" aria-description=Homepage><svg id="logotype" width="308pt" aria-label="ResCon 2026"><text id="logotype__text" y="19.5pt" x="0" style="text-transform:none">ResCon 2026</text></svg></a><details class=presentation id=top-nav><summary class=on-deck><span class="t t2">Navigation</span>
<span class=menu-icon role=presentation></span></summary><nav tabindex=-1 aria-label=Top><details id=has-main-menu class=presentation open><summary class=hide aria-label="Main Menu"><span>Main Menu</span></summary><nav id=main-menu aria-label="Main Menu"><ul class=l1 role=presentation tabindex=-1><li role=presentation><a class=on-deck href={{ $base }}/rescon/><span>Home</span></a></li><li role=presentation><a class=on-deck href={{ $base }}/rescon/detail/programme/><span>Programme</span></a></li><li role=presentation><a class=on-deck href={{ $base }}/rescon/detail/speakers/><span>Speakers</span></a></li><li role=presentation><a class=on-deck href={{ $base }}/rescon/detail/dates/><span>Dates</span></a></li><li role=presentation><a class=on-deck href=https://unstop.com/p/techconnect26-research-poster-presentation-competition-iit-bombay-1749312 target=_blank><span>Register</span></a></li><li role=presentation><details class="presentation js-details" aria-expanded=true name=on-deck><summary class="anchor on-deck"><span>Gallery</span></summary><ul class="l2 on-plank" role=presentation><li role=presentation><a class=has-desc href={{ $base }}/rescon/detail/gallery/ aria-label="Gallery 2025" aria-description="Moments from ResCon 2025"><span>Gallery 2025</span></a></li><li role=presentation><a class=has-desc href={{ $base }}/rescon/detail/highlights/ aria-label="Highlights 2024" aria-description="ResCon 2024 highlights"><span>Highlights 2024</span></a></li></ul><div class="screening js-cpn" role=presentation aria-hidden=true></div></details></li><li role=presentation><a class=on-deck href={{ $base }}/rescon/detail/contact/><span>Contact</span></a></li></ul></nav></details><details id=has-search class="presentation js-details" name=on-deck><summary class="on-deck srm" accesskey=q aria-labelledby=search-label aria-keyshortcuts=q><span id=search-label class="t t2 srt">Search</span></summary><div id=search class=on-hull><div role=presentation class="screening js-cgpn"></div></div><script src=/rescon-assets/pagefind/pagefind-ui.js type=text/javascript></script><script>let pageFindInitialized=!1;const initPageFind=function(){if(!pageFindInitialized){new PagefindUI({element:"#search",baseUrl:"/rescon",showImages:!1,translations:{placeholder:"Search"}});const e=document.querySelector(".pagefind-ui__search-input");e&&e.setAttribute("aria-label",e.getAttribute("placeholder")),pageFindInitialized=!0,document.removeEventListener("DOMContentLoaded",initPageFind)}};document.addEventListener("DOMContentLoaded",initPageFind)</script><noscript id=has-search-fallback class=on-hull><form id=duckduckgo class="form on-plank" name=x action=//duckduckgo.com/ role=search aria-label="[i18n] searchDuckDuckGo"><input type=hidden value=rnd.iitb.ac.in name=sites></input>
<input type=hidden value=1 name=kh></input>
<input type=hidden value=1 name=kn></input>
<input type=hidden value=1 name=kac></input>
<input class="ldots form__input" type=search placeholder=Search name=q role=searchbox></input>
<button class=form__button type=submit aria-label=Search>
<img src=https://duckduckgo.com/assets/logo_header.v109.svg alt role=presentation aria-hidden=true></button></form><div role=presentation class="screening js-cgpn"></div></noscript></details><details id=has-more-menu class="presentation js-details" name=on-deck><summary accesskey="=" class="on-deck srm" aria-label="More Menu"><span class="t t2 srt">More Menu</span>
<span class="menu-icon sri" role=presentation></span></summary><nav id=more-menu aria-label="More Menu"><ul class="l1 on-plank has-childfree" role=presentation tabindex=-1><li role=presentation><a class=has-desc href=/ target=_blank aria-label=TechConnect aria-description="Link to TechConnect"><span>TechConnect</span></a></li></ul><div class="screening js-cgpn" role=presentation aria-hidden=true></div></nav></details></nav><div id=top-nav-screen class="screening js-cpn" role=presentation aria-hidden=true></div></details></header>